# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tdv20/Documents/SoC_Project/ZynqBerry_TE0726-03/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_i2s_receiver_0_0/zsys_i2s_receiver_0_0.xci
# IP: The module: 'zsys_i2s_receiver_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tdv20/Documents/SoC_Project/ZynqBerry_TE0726-03/zynqberrydemo1/vivado/zynqberrydemo1.gen/sources_1/bd/zsys/ip/zsys_i2s_receiver_0_0/zsys_i2s_receiver_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_i2s_receiver_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/tdv20/Documents/SoC_Project/ZynqBerry_TE0726-03/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ip/zsys_i2s_receiver_0_0/zsys_i2s_receiver_0_0.xci
# IP: The module: 'zsys_i2s_receiver_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tdv20/Documents/SoC_Project/ZynqBerry_TE0726-03/zynqberrydemo1/vivado/zynqberrydemo1.gen/sources_1/bd/zsys/ip/zsys_i2s_receiver_0_0/zsys_i2s_receiver_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_i2s_receiver_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
